const swaggerJsdoc = require('swagger-jsdoc');

// swaggerJsdoc takes an options object and returns a fully-formed OpenAPI JSON document
// It does this by scanning the files listed in `apis` for @openapi JSDoc comments
const options = {

  // `definition` is the top-level OpenAPI document structure
  // This is metadata about your API — not the endpoints themselves
  definition: {
    openapi: '3.0.0',           // The OpenAPI specification version we're following

    info: {
      title: 'Smart Expense Tracker API',
      version: '1.0.0',
      description:
        'A REST API for tracking personal expenses. ' +
        'Built with Express.js, UUID, and a local JSON file as the data store. ' +
        'Supports creating, listing, filtering, totalling, and deleting expenses.',
    },

    servers: [
      {
        // The base URL where the API is running
        // Swagger UI will prepend this to all endpoint paths when making test requests
        url: 'http://localhost:3000',
        description: 'Local development server',
      },
    ],

    // Reusable components — define schemas once, reference them everywhere
    // This avoids copy-pasting the same object shape across multiple endpoint docs
    components: {
      schemas: {

        // The shape of a single expense object (as returned by the API)
        Expense: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              format: 'uuid',
              description: 'Unique identifier generated by UUID v4',
              example: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
            },
            title: {
              type: 'string',
              description: 'Short description of the expense',
              example: 'Coffee',
            },
            amount: {
              type: 'number',
              description: 'Cost of the expense in the local currency',
              example: 4.5,
            },
            category: {
              type: 'string',
              description: 'Category the expense belongs to',
              example: 'Food',
            },
            date: {
              type: 'string',
              format: 'date-time',
              description: 'ISO 8601 timestamp when the expense was created',
              example: '2026-08-01T10:30:00.000Z',
            },
          },
        },

        // The shape of the request body when creating an expense
        CreateExpenseBody: {
          type: 'object',
          required: ['title', 'amount', 'category'],  // These fields must be present
          properties: {
            title: {
              type: 'string',
              example: 'Coffee',
            },
            amount: {
              type: 'number',
              example: 4.5,
            },
            category: {
              type: 'string',
              example: 'Food',
            },
          },
        },

        // Reusable validation error response shape
        ValidationError: {
          type: 'object',
          properties: {
            errors: {
              type: 'array',
              items: { type: 'string' },
              example: ['title is required and must be a non-empty string'],
            },
          },
        },

        // Reusable general error response shape (404, 500)
        ErrorResponse: {
          type: 'object',
          properties: {
            error: {
              type: 'string',
              example: "Expense with id 'abc-123' not found",
            },
          },
        },

        // Shape of the total endpoint response
        TotalResponse: {
          type: 'object',
          properties: {
            total: {
              type: 'number',
              example: 17.0,
            },
            category: {
              type: 'string',
              example: 'all',
            },
            count: {
              type: 'integer',
              example: 3,
            },
          },
        },

      },
    },
  },

  // Tell swagger-jsdoc which files to scan for @openapi comments
  // It reads the JSDoc annotations and merges them into the spec
  apis: ['./src/routes/*.js'],
};

// Generate and export the final OpenAPI specification object
// This is what swagger-ui-express will use to render the docs page
const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;
